# Generated by Django 2.1.1 on 2018-09-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcos_api', '0002_auto_20180911_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='gps_longitute',
            new_name='gps_longitude',
        ),
    ]
