# Generated by Django 2.1.1 on 2018-09-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcos_api', '0002_userprofile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
