# Generated by Django 2.1.1 on 2018-09-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcos_api', '0003_auto_20180907_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='name',
        ),
    ]
