# Generated by Django 2.1.1 on 2018-09-14 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcos_api', '0004_auto_20180912_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
